### PR TITLE
Review

### PR DESCRIPTION
**Pull request by k-rtik**
- Concise title
- Replaced Amazon and Google custom providers with LinkedIn configuration provided by Open Liberty
- Formatted "What you will learn" section to be similar to the CORS guide

### CODE REVIEW

**Comment by yeekangc** [comment]
Custom providers can be mentioned as advanced options that users can consider if they need to.  For a guide and a first one, we can focus on the built-in providers.

**Comment by yeekangc** [comment]
Be sure to review front matter including categories and related guides.

**Comment by yeekangc** [comment]
The style doesn't appear to be consistent with the other guides.  Please keep in mind that guides aren't procedural product documentation.  Please take note and revise accordingly.

Tagging @lauracowen if she wouldn't mind taking a quick look and offer her initial thoughts.

**Comment by lauracowen** [comment]
Further to what @yeekangc said, we need the introduction (what you'll learn) to be more punchy and focused, rather than documentation. I'll re-draft you something. I can do it as a separate PR or issue if you like? Or I can paste it here when I'm done.

**Comment by k-rtik** [comment]
image

**Pull request closed without merging**
